zsh: merge .zshrc from various sources

diff --git a/zshrc-obsolete b/zshrc-obsolete
--- a/zshrc-obsolete
+++ b/zshrc-obsolete
@@ -1,3 +1,351 @@
 # Old zsh utilities that I stopped using
 
+alias getallphotos='for i in `seq 1 120` ; do photopc image $i pic`echo $i + 1000 | bc | cut -b 2-4`.jpeg ; done'
+alias cvs_videolan='cvs -d :pserver:sam@cvs.videolan.org:/var/cvs/videolan'
+alias cvs_cnedra='cvs -d :pserver:sam@cvs.via.ecp.fr:/var/cvs/cnedra'
+alias cvs_sam='cvs -d :pserver:sam@cvs.via.ecp.fr:/var/cvs/sam'
+alias cvs_gnome='cvs -d :pserver:anonymous@anoncvs.gnome.org:/cvs/gnome'
+alias cvs_mjdrdm2='cvs -d :pserver:sam@cvs.nimp.org:/var/cvs/mjdrdm2'
+alias cvs_quake='cvs -d:pserver:anonymous@cvs.quake.sourceforge.net:/cvsroot/quake'
+alias cvs_galeon='cvs -d:pserver:anonymous@cvs.galeon.sourceforge.net:/cvsroot/galeon'
+alias cvs_dacode='cvs -d:pserver:anonymous@cvs.dacode.sourceforge.net:/cvsroot/dacode'
+alias cvs_berlin='cvs -d:pserver:anonymous@cvs.berlin.sourceforge.net:/cvsroot/berlin'
+alias cvs_livid='cvs -d:pserver:anonymous@cvs.linuxvideo.org:/cvs/livid'
+
+rwget () { wget --header "Referer: $1" $* }
+
+compctl -g '*.ps' + -g '*' ggv
+
+alias btdownloadcurses='btdownloadcurses --max_upload_rate 1'
+alias btlaunchmanycurses='btlaunchmanycurses --max_upload_rate 1'
+alias dchroot='schroot -pc'
+alias d4='P4CONFIG=.p4config-data p4'
+alias antlr3.4='java org.antlr.Tool'
+
+# Create a new-style mailbox
+mkmailbox() {
+    mkdir -p ~/mail/"$1"/cur
+    mkdir -p ~/mail/"$1"/tmp
+    mkdir -p ~/mail/"$1"/new
+}
+
+# Debian development stuff
+debupload () { scp $* sho@auric.debian.org:/org/ftp.debian.org/incoming }
+debupload-nonus () { scp $* sho@pandora.debian.org:/org/non-us.debian.org/incoming }
+
+apt-rbdepends () { grep-dctrl -F Build-Depends "$1" -s Package /var/lib/apt/lists/*_Sources }
+
+clean-build-areas() {
+  df ~
+  rm -Rf ~/debian/pkg-*/*/build-area/[a-z]*
+  df ~ | tail -1
+}
+
+alias export-quilt-patches='export QUILT_PATCHES=debian/patches'
+
+raspi-install() {
+    for pkg in "$@"; do
+        apt-get download --allow-unauthenticated "$pkg":armhf && dpkg-deb -x "$pkg"_*.deb $RASPI_SDK_ROOT/chroot && rm -f "$pkg"_*_armhf.deb
+    done
+}
+
+# big-endian hexdump
+hex () { hexdump $* | sed 's/ \(..\)\(..\)/\2\1/g' | cut -b 8-80 }
+
+# alias for quick Debian package builds
+alias dpkg-builddirtypackage='chmod +x debian/rules && dpkg-buildpackage -rfakeroot -us -uc'
+
+# Flush IPCs (back to the 90s)
+ipcflush () {
+  IPCS="`ipcs | awk '{ if ($6 == 0) print $2 }'`"
+  echo -n "ipcflush: "
+  test "$IPCS" && ipcrm shm `echo $IPCS` || echo "nothing to flush."
+}
+
+# Get message from a news server
+mid() { (echo "mode reader" ; echo "article <$*>" | sed 's/%40/@/ ; s/%24/\$/g ; s/<<*/</g ; s/>>*/>/g' ) | tee /dev/stderr | nc news 119 | tail -n +3 }
+
+# Start doing something when a host can be pinged
+pingwait () {
+  until fping -q $* 2>/dev/null 2>&1
+  do
+    sleep 5
+  done
+}
+
+# Increase volume progressively (I was using that in the 90s to wake up)
+volinc() { for i in `seq $1 $2` ; do aumix -v $i ; sleep $3 ; done }
+
+# Can’t remember what this does
+alias mixlines='awk ''{ printf "%s %i\n", $0, NR }''|rev|tr 0-9azertyuiop azertyuiop0-9|sort|cut -f2- -d'' ''|tr 0-9azertyuiop azertyuiop0-9|rev'
+customseq() { i=$1 ; while test $i -lt `expr $2 + 1` ; do echo $i ; i=`expr $i + 1` ; done }
+
+# SSH known hosts completion
+if [ -r ~/.ssh/known_hosts ]
+then
+  hosts=(`sed 's/^\([[:alnum:]\.]*\).*/\1/' < ~/.ssh/known_hosts`)
+  compctl -k hosts -x 'c[-1,-l]' -u -- + -x 'm[2,2]' -u -S "@" -- + -x 'n[1,@]' -k hosts -- ssh
+  compctl -f + -k hosts -S ":" + -u -S "@" -x 'n[1,@]' -k hosts -S ":" -- scp
+fi
+
+# Stuff from when I worked at SNCF
+noproxy() { unset http_proxy; unset ftp_proxy }
+sncf() { export http_proxy="http://proxy.dr.sncf.fr:8080/" ftp_proxy="http://proxy.dr.sncf.fr:8080/"; export no_proxy="dr.sncf.fr,sncf.fr" }
+#sncf() { export http_proxy="http://10.13.200.19:8080/" ftp_proxy="ftp://10.13.200.19:21/"; export no_proxy="dr.sncf.fr,sncf.fr" }
+localproxy() { export http_proxy="http://localhost:8080/" ftp_proxy="http://localhost:8080/"; export no_proxy="dr.sncf.fr,sncf.fr" }
+
+# Retarget CVS repository
+setcvshost() {
+  test -d CVS \
+    && (find -name Root | while read i ; do \
+            sed 's/@[^:]*:/@'"$1"':/' < "$i" >| "$i.bak" ; \
+            mv -f "$i.bak" "$i" ; done) \
+    || (echo "not in a CVS directory" && false)
+}
+
+# Retarget SVN repository
+setsvnroot() {(
+  if [ ! -f .svn/entries ]; then
+    echo "$0: not in a SVN repository"
+    return 1
+  fi
+  while [ -f ../.svn/entries ]; do
+    cd ..
+    echo "$0: climbing up to "'`'"`pwd`' ..."
+  done
+  ROOT="`sed -ne 's%.*url="\([^"]*\)".*%\1%p' < .svn/entries`"
+  case "$ROOT" in
+    file:///*)
+      PROTO="file"
+      LOGIN=""
+      REPOS="`echo "$ROOT" | cut -b8-`"
+      ;;
+    svn://*/*)
+      PROTO="svn"
+      LOGIN="`echo "$ROOT" | cut -f3 -d/`"
+      REPOS="/`echo "$ROOT" | cut -f4- -d/`"
+      ;;
+    svn+ssh://*/*)
+      PROTO="svn+ssh"
+      LOGIN="`echo "$ROOT" | cut -f3 -d/`"
+      REPOS="/`echo "$ROOT" | cut -f4- -d/`"
+      ;;
+    *)
+      echo "$0: unrecognised root -- $ROOT"
+      return 1
+      ;;
+  esac
+  NEWPROTO=""
+  NEWLOGIN=""
+  NEWREPOS=""
+  while test $# -gt 0; do
+    case "$1" in
+      -p) NEWPROTO="$2"; ;;
+      -h) NEWLOGIN="$2"; ;;
+      -r) NEWREPOS="$2"; ;;
+      *) echo "$0: unknown option -- $1"; INVALID=yes; break; ;;
+    esac
+    if [ $# = 1 ]; then
+      echo "$0: missing argument -- $1"
+      return 1
+    fi
+    shift
+    shift
+  done
+  if [ -z "$NEWPROTO" -a -z "$NEWLOGIN" -a -z "$NEWREPOS" ] || [ -n "$INVALID" ]; then
+    echo "Usage:"
+    echo "  $0 [-p proto] [-h host] [-r repository]"
+    echo "Examples:"
+    echo "  $0 -h foo@svn.domain.com"
+    echo "  $0 -p svn -h svn.domain.com -r /var/svn/module"
+    echo "  $0 -p svn+ssh -h svn.domain.com -r /var/svn/module"
+    echo "  $0 -p file"
+    echo "Current root:"
+    echo "  $ROOT"
+    return 1
+  fi
+  # test the protocol validity
+  case "$NEWPROTO" in
+    file)
+      if [ -n "$NEWLOGIN" ]; then
+        echo "$0: cannot specify -h with file://"
+        return 1
+      fi
+      if [ -z "$NEWREPOS" ]; then NEWREPOS="$REPOS"; fi
+      ;;
+    svn+ssh|svn)
+      if [ -z "$NEWLOGIN" -a -z "$LOGIN" ]; then
+        echo "$0: -h is needed to change protocol to svn+ssh/svn"
+        return 1
+      fi
+      if [ -z "$NEWLOGIN" ]; then NEWLOGIN="$LOGIN"; fi
+      if [ -z "$NEWREPOS" ]; then NEWREPOS="$REPOS"; fi
+      ;;
+    "")
+      if [ -n "$NEWLOGIN" -a "$PROTO" = "file" ]; then
+        NEWPROTO="svn+ssh"
+      else
+        NEWPROTO="$PROTO"
+      fi
+      if [ -z "$NEWLOGIN" ]; then NEWLOGIN="$LOGIN"; fi
+      if [ -z "$NEWREPOS" ]; then NEWREPOS="$REPOS"; fi
+      ;;
+    *)
+      echo "$0: unknown protocol -- $NEWPROTO"
+      return 1
+      ;;
+  esac
+  case "$NEWREPOS" in
+    /*)
+      ;;
+    *)
+      echo "$0: repository must start with /"
+      return 1
+      ;;
+  esac
+  # do the job
+  echo "$0: changing url to $NEWPROTO://$NEWLOGIN$NEWREPOS"
+  find -name entries | while read i;
+    do sed -e 's%\(url\|repos\)="'"$ROOT"'%\1="'"$NEWPROTO://$NEWLOGIN$NEWREPOS"'%' < "$i" >| "$i.bak"
+    mv -f "$i.bak" "$i"
+  done
+  echo "done."
+)}
+
+# Get all images linked or embedded in a web page
+getallimages() {
+   _getallimages_inner "href" "$@"
+}
+
+getallembed() {
+   _getallimages_inner "src" "$@"
+}
+
+_getallimages_inner() {
+  TAG="$1"
+  shift
+  while test "$#" -gt 0; do
+    URL="$1"
+    DIR=`echo "$URL" | sed 's/[^a-zA-Z0-9_.-]/-/g'`
+    PREFIX=`echo "$1" | sed 's@^\(.*/\).[^/]*$@\1@'`
+    PROTO="http" # FIXME
+    ROOT=`echo "$1" | sed 's@\(://[^/]*\)/.*$@\1@'`
+    mkdir -p "$DIR"
+    ( cd "$DIR"
+      wget --cache=no -O - -U 'Mozilla/5.0' "$URL" | tr '>' '\n' | grep -i "$TAG" | sed 's/.*'"$TAG"' *=[ "]*//i ; s/[" ].*//g' | grep -i '\(jpe\|jpg\|jpeg\|gif\|mpg\|mpeg\|avi\|wmv\)$' | grep -v '/src[.]cgi/' | sort | uniq | while read IMAGE
+      do
+        if echo "$IMAGE" | grep -qi "^//"; then IMAGE="$PROTO:$IMAGE"; else
+        if echo "$IMAGE" | grep -qi "^/"; then IMAGE="$ROOT/$IMAGE"; else
+        if echo "$IMAGE" | grep -vqi "^http"; then IMAGE="$PREFIX/$IMAGE"; fi; fi; fi
+        echo "$IMAGE"
+        wget -c -U 'Mozilla/5.0' --header "Referer: $URL" "$IMAGE" 2>&1 | grep '\(\[\|fully retrieved\)'
+      done
+    ) # cd ..
+    shift
+  done
+}
+
+# Get bug information from some websites
+getbug_debian() {
+    wget 'http://bugs.debian.org/cgi-bin/bugreport.cgi?archive=no&bug='"$1" -O "$1"'.html'
+}
+
+getbugs() {
+    wget -O - 'http://bugzilla.videolan.org/cgi-bin/bugzilla/buglist.cgi?short_desc_type=allwordssubstr&short_desc=&long_desc_type=allwordssubstr&long_desc=&bug_file_loc_type=allwordssubstr&bug_file_loc=&bug_status=NEW&bug_status=ASSIGNED&bug_status=REOPENED&emailtype1=substring&email1=&emailtype2=substring&email2=&bugidtype=include&bug_id=&changedin=&chfieldfrom=&chfieldto=Now&chfieldvalue=&cmdtype=doit&newqueryname=&order=Reuse+same+sort+as+last+time&field0-0-0=noop&type0-0-0=noop&value0-0-0='
+}
+
+getlongbugs() {
+    wget -O - 'http://bugzilla.videolan.org/cgi-bin/bugzilla/long_list.cgi?buglist='`getbugs | grep 'hidden.*buglist' | cut -f6 -d'"' | tr , '\n' | sort -n | tr '\n' ,`
+}
+
+# Stuff from when I worked at Uniways
+rdesktop-c18() { rdesktop -K -D -k fr -g 1024x768 $* }
+rdesktop-uniways() { rdesktop -K -D -k en-us -g 1400x1050 192.168.1.54 }
+rdesktop-uniways-proxychains() { proxychains rdesktop -K -D -k en-us -g 1400x1050 192.168.1.54 }
+rdesktop-dontnod() { rdesktop -K -D -k en-us -g 1400x1050 192.168.204.2 }
+
+# ispic(): checks whether a binary object, either a .o or a .so file, has
+# only PIC code in it. It can also inspect .o files within a .a archive.
+ispic() {
+   ispic_internal() {
+      if objdump --headers --private-headers -T "$1" | grep -q TEXTREL; then
+         echo -e "$2"': \x1b[31;1mhas non-PIC code\x1b[0m'
+      else
+         echo -e "$2"': \x1b[32;1mPIC\x1b[0m'
+      fi
+   }
+   for x in $*; do
+      TMPFILE="`tempfile -s .so`"
+      case "$x" in
+         *.a)
+            echo "$x: archive"
+            TMPOFILE="`tempfile -s .o`"
+            for o in `ar t "$x"`; do
+               ar p "$x" "$o" >| "$TMPOFILE"
+               ispic "$TMPOFILE" | sed 's .*: \ \ '"$o"': '
+            done
+            rm -f "$TMPOFILE"
+            ;;
+         *.o|*.so|*.so.*)
+            case "$x" in
+               *.so|*.so.*)
+                  ispic_internal "$x" "$x"
+                  ;;
+               *.o)
+                  if gcc "$x" -shared -o "$TMPFILE" 2>&1 | grep -q relocation; then
+                     echo -e "$x"': \x1b[31;1mbad reloc, non-PIC code\x1b[0m'
+                  else
+                     ispic_internal "$TMPFILE" "$x"
+                  fi
+                  ;;
+            esac
+            ;;
+      esac
+      rm -f "$TMPFILE"
+   done
+}
+
+# Same as ispic() for executable stack
+hasxstack() {
+   hasxstack_internal() {
+      STACK="`objdump --headers --private-headers -T "$1" | grep -A1 STACK | sed -ne 's/.*flags //p'`"
+      case "$STACK" in
+      *x) echo -e "$2"': \x1b[31;1mhas executable stack ('"$STACK"')\x1b[0m' ;;
+      *) echo -e "$2"': \x1b[32;1mstack is OK ('"$STACK"')\x1b[0m' ;;
+      esac
+   }
+   for x in $*; do
+      TMPFILE="`tempfile -s .so`"
+      case "$x" in
+         *.a)
+            echo "$x: archive"
+            TMPOFILE="`tempfile -s .o`"
+            for o in `ar t "$x"`; do
+               ar p "$x" "$o" >| "$TMPOFILE"
+               hasxstack "$TMPOFILE" | sed 's .*: \ \ '"$o"': '
+            done
+            rm -f "$TMPOFILE"
+            ;;
+         *.o|*.so|*.so.*)
+            case "$x" in
+               *.so|*.so.*)
+                  hasxstack_internal "$x" "$x"
+                  ;;
+               *.o)
+                  if gcc "$x" -shared -o "$TMPFILE" 2>&1 | grep -q relocation; then
+                     echo -e "$x"': \x1b[31;1mbad reloc, cannot check stack\x1b[0m'
+                  else
+                     hasxstack_internal "$TMPFILE" "$x"
+                  fi
+                  ;;
+            esac
+            ;;
+      esac
+      rm -f "$TMPFILE"
+   done
+}
+
+# Stuff from my work at Don’t Nod
+alias nimp-upgrade='pip3 install --upgrade git+https://github.com/dontnod/nimp.git'
+scan-vnc() { ssh root@max nmap -oG - -p5900 --open 172.20.100.0/24 }
 
